volumes:
  db-data:

networks:
  micro-net:
    driver: bridge

services:
  vote:
    image: jatisatrio/web-hextris
    build: ./web-hextris
    ports:
      - 6000:80
    depends_on:
      - redis
    networks:
      - micro-net